spring.application.name=AirBnb

# DB Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/airbnb_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=tripathi1810
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.servlet.context-path=/api/v1
server.port=8080

# JWT Secret
jwt.secretKey=${JWT_SECRET}

# Frontend URL
frontend.url=${FRONTEND_URL}

# Stripe Configuration
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# Swagger Configuration
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
